export const FETCH_COUNTRIES ='FETCH_COUNTRIES'; 
export const SEARCH_COUNTRIES ='SEARCH_COUNTRIES'; 
export const FILTER_COUNTRIES ='FILTER_COUNTRIES'; 
export const FETCH_COUNTRY ='FETCH_COUNTRY';
export const FETCH_BORDERS ='FETCH_BORDERS';
export const DARK_MODE = 'DARK_MODE';